package cmd

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/jbakchr/hewd/internal/api"
	"github.com/jbakchr/hewd/internal/cliutils"
	"github.com/jbakchr/hewd/internal/diff"
	"github.com/jbakchr/hewd/internal/helptext"
)

func newDiffCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:     helptext.DiffUse,
		Short:   helptext.DiffShort,
		Long:    helptext.DiffLong,
		Example: helptext.DiffExample,
		Args:    cobra.ExactArgs(2),

		RunE: func(cmd *cobra.Command, args []string) error {

			// -----------------------------------------------------------------
			// Parse output flags
			// -----------------------------------------------------------------
			jsonOut, _ := cmd.Flags().GetBool("json")
			yamlOut, _ := cmd.Flags().GetBool("yaml")
			mdOut, _ := cmd.Flags().GetBool("md")
			pretty, _ := cmd.Flags().GetBool("pretty")

			if err := cliutils.ValidateOutputFormatFlags(jsonOut, yamlOut, mdOut, pretty, "diff"); err != nil {
				return err
			}

			failScoreDrop, _ := cmd.Flags().GetInt("fail-on-score-drop")
			failNewErrors, _ := cmd.Flags().GetBool("fail-on-new-errors")
			failAny, _ := cmd.Flags().GetBool("fail-on-any-regression")

			oldPath := args[0]
			newPath := args[1]

			// -----------------------------------------------------------------
			// Load old report
			// -----------------------------------------------------------------
			oldData, err := os.ReadFile(oldPath)
			if err != nil {
				return cliutils.ErrHint(
					fmt.Sprintf("failed to read file %s: %v", oldPath, err),
					"ensure the file exists and is readable",
				)
			}

			var oldReport api.MachineOutput
			if err := json.Unmarshal(oldData, &oldReport); err != nil {
				return cliutils.ErrHint(
					fmt.Sprintf("failed to parse json in %s: %v", oldPath, err),
					"use a report generated by `hewd export`",
				)
			}

			// -----------------------------------------------------------------
			// Load new report
			// -----------------------------------------------------------------
			newData, err := os.ReadFile(newPath)
			if err != nil {
				return cliutils.ErrHint(
					fmt.Sprintf("failed to read file %s: %v", newPath, err),
					"ensure the file exists and is readable",
				)
			}

			var newReport api.MachineOutput
			if err := json.Unmarshal(newData, &newReport); err != nil {
				return cliutils.ErrHint(
					fmt.Sprintf("failed to parse json in %s: %v", newPath, err),
					"use a report generated by `hewd export`",
				)
			}

			// -----------------------------------------------------------------
			// Schema version check
			// -----------------------------------------------------------------
			if oldReport.SchemaVersion != newReport.SchemaVersion {
				return cliutils.ErrHint(
					fmt.Sprintf("schema version mismatch: old=%d new=%d",
						oldReport.SchemaVersion, newReport.SchemaVersion),
					"regenerate both reports using the same version of hewd",
				)
			}

			// -----------------------------------------------------------------
			// Compute diff
			// -----------------------------------------------------------------
			result := diff.ComputeDiff(&oldReport, &newReport)

			gate := diff.EvaluateRegressionGates(
				result,
				failScoreDrop,
				failNewErrors,
				failAny,
			)

			if gate.Failed {
				if !jsonOut && !yamlOut {
					fmt.Println("\n❌ Regression detected:")
					for _, r := range gate.Reasons {
						fmt.Printf(" - %s\n", r)
					}
				}

				return cliutils.ErrHint(
					"regression gating failed",
					"address regressions or adjust CI gating logic",
				)
			}

			// Prepare machine-friendly diff output
			out := diff.MakeDiffOutput(result, &oldReport, &newReport)

			// -----------------------------------------------------------------
			// JSON output
			// -----------------------------------------------------------------
			if jsonOut {
				var data []byte
				if pretty {
					data, err = json.MarshalIndent(out, "", "  ")
				} else {
					data, err = json.Marshal(out)
				}
				if err != nil {
					return cliutils.ErrHint(
						fmt.Sprintf("failed to marshal json: %v", err),
						"ensure the diff output is valid json",
					)
				}

				fmt.Println(string(data))
				return nil
			}

			// -----------------------------------------------------------------
			// YAML output
			// -----------------------------------------------------------------
			if yamlOut {
				data, err := yaml.Marshal(out)
				if err != nil {
					return cliutils.ErrHint(
						fmt.Sprintf("failed to marshal yaml: %v", err),
						"ensure the diff output is valid yaml",
					)
				}

				fmt.Println(string(data))
				return nil
			}

			// -----------------------------------------------------------------
			// Markdown output
			// -----------------------------------------------------------------
			if mdOut {
				md := diff.WriteMarkdown(result, oldReport, newReport)
				fmt.Println(md)
				return nil
			}

			// -----------------------------------------------------------------
			// Pretty output (default)
			// -----------------------------------------------------------------
			return writePrettyDiff(result)
		},
	}

	cmd.GroupID = "analysis"

	// Flags
	cmd.Flags().Bool("json", false, "Output diff results in JSON format. Use --pretty for indented JSON.")
	cmd.Flags().Bool("yaml", false, "Output diff results in YAML format.")
	cmd.Flags().Bool("md", false, "Output diff results in Markdown format.")
	cmd.Flags().Bool("pretty", false, "Pretty-print JSON output for readability.")

	cmd.Flags().Int("fail-on-score-drop", 0, "Fail if score drops by N or more points.")
	cmd.Flags().Bool("fail-on-new-errors", false, "Fail if any new error-level issues appear.")
	cmd.Flags().Bool("fail-on-any-regression", false, "Fail on any regression (score drop or new issues).")

	return cmd
}
