name: hewd

on:
  pull_request:

jobs:
  hewd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install hewd
        run: |
          go build -o hewd ./cmd/hewd

      - name: Run hewd action
        uses: ./.github/actions/hewd-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-comment: true
          md-report: true
